server {
    listen 80;
    server_name {domain};

    # Foydalanuvchi so'rov yuborgan asosiy manzillar
    location ~ ^/(api|webhook|docs|openapi.json) {
        # Nginx kelgan so'rov oxiriga (/docs, /api va h.k.) 
        # avtomatik ravishda /{name} prefiksini qo'shib ichkariga otadi
        proxy_pass http://127.0.0.1:8000/{name}$request_uri;
        
        # Standart proxy sarlavhalari (FastAPI hammasini to'g'ri anglashi uchun)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}