server {
    listen 80;
    server_name {domain};

    # Barcha so'rovlarni tutib oluvchi asosiy blok
    location / {
        # Kelgan so'rovni (masalan /docs) ichkariga /{name}/docs qilib o'zgartiradi
        # "break" buyrug'i bu jarayonni takrorlanishdan saqlaydi (duplikat bo'lmaydi)
        rewrite ^/(.*)$ /{name}/$1 break;

        # O'zgartirilgan so'rovni uvicorn (manager_app) manziliga yuborish
        proxy_pass http://127.0.0.1:8000;
        
        # Standart proxy sarlavhalari (FastAPI hammasini to'g'ri anglashi uchun)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}