server {
    listen 80;
    server_name ~^(?<project_domain>.+)$; # Kelgan har qanday domenni tutib oladi

    location / {
        # projects.yaml dagi loyiha nomi 'project_domain' bilan bir xil bo'lishi kerak
        proxy_pass http://127.0.0.1:8000/$project_domain/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}